/**
 * Type definitions for Memory API responses and SSE streaming events.
 * These interfaces reflect the WhyDecisionResponse@1 schema and
 * streaming token semantics described in the technical spec.
 */

export interface EvidenceItem {
  id: string;
  summary?: string;
  timestamp?: string;
  rationale?: string;
  snippet?: string;
  tags?: string[];
  based_on?: string[];
<<<<<<< HEAD
  decision_maker?: string;
=======
>>>>>>> origin/main
}

export interface EvidenceBundle {
  anchor: EvidenceItem;
  events: EvidenceItem[];
  transitions?: {
    preceding?: EvidenceItem[];
    succeeding?: EvidenceItem[];
  };
  allowed_ids: string[];
}

export interface WhyDecisionAnswer {
  short_answer: string;
  supporting_ids: string[];
  rationale_note?: string;
}

export interface CompletenessFlags {
  has_preceding: boolean;
  has_succeeding: boolean;
  event_count: number;
}

export interface MetaInfo {
  policy_id: string;
  prompt_id: string;
  retries: number;
  latency_ms: number;
  function_calls?: string[];
  routing_confidence?: number;
  prompt_fingerprint?: string;
  snapshot_etag?: string;
  fallback_used?: boolean;
<<<<<<< HEAD
  fallback_reason?: string;
=======
>>>>>>> origin/main
  /**
   * Unique request identifier generated by the backend. Used for tracing and
   * correlating logs. Optional because earlier schema versions did not
   * include it.
   */
  request_id?: string;

  /**
   * Deterministic fingerprint of the execution plan used by the agent. When
   * present, this can be surfaced in the audit drawer. Optional.
   */
  plan_fingerprint?: string;

  /**
   * Alternate name for the prompt fingerprint emitted by some backends.
   * When provided, the UI should favour prompt_fingerprint over
   * prompt_envelope_fingerprint but fall back gracefully.
   */
  prompt_envelope_fingerprint?: string;

  /**
   * Mapping of evidence IDs to selector scores; used to visualise evidence
   * selection confidences. Optional.
   */
  selector_scores?: Record<string, number>;

  /**
   * IDs of evidence items that were dropped by the selector. Optional.
   */
  dropped_evidence_ids?: string[];

  /**
   * High‑level trace of pipeline stages executed by the backend. Optional.
   */
  trace?: string[];

  /**
   * Raw prompt envelope object sent to the LLM. Optional.
   */
  prompt_envelope?: unknown;

  /**
   * Rendered prompt string delivered to the LLM after variable substitution. Optional.
   */
  rendered_prompt?: string;

  /**
   * Raw JSON returned by the language model before validation. Optional.
   */
  raw_llm_json?: unknown;

  /**
   * Indicates whether the response was served from cache. Optional.
   */
  cache_hit?: boolean;
  // Evidence bundling & prompt budget metrics (M3/M5)
  // See spec: total_neighbors_found, selector_truncation, bundle_size_bytes, max_prompt_bytes
  // and final_evidence_count for post-truncation bundle size.
  total_neighbors_found?: number;
  selector_truncation?: boolean;
  final_evidence_count?: number;
  bundle_size_bytes?: number;
  max_prompt_bytes?: number;
}



export interface WhyDecisionResponse {
  intent: string;
  evidence: EvidenceBundle;
  answer: WhyDecisionAnswer;
  completeness_flags: CompletenessFlags;
  meta: MetaInfo;
<<<<<<< HEAD
  bundle_url?: string;
=======
>>>>>>> origin/main
}

/**
 * Shape of streaming events delivered by the Memory API. During streaming,
 * events may contain a single token, and the final event will contain
 * the complete response including answer and evidence.
 */
export interface StreamEvent {
  token?: string;
  final?: boolean;
  answer?: WhyDecisionAnswer;
  evidence?: EvidenceBundle;
  meta?: MetaInfo;
  error?: any;
}

/**
 * Schema field grouping returned by /v2/schema/fields. The key is a
 * semantic name and the value is an array of synonyms or field identifiers.
 */
export type SchemaFields = Record<string, string[]>;

/**
 * Single relationship entry returned by /v2/schema/rels.
 */
export interface SchemaRelation {
  from: string;
  to: string;
  relation: string;
}

export interface EvidenceItem {
  id: string;
  summary?: string;
  timestamp?: string;
  rationale?: string;
  snippet?: string;
  tags?: string[];
  based_on?: string[];
<<<<<<< HEAD
  decision_maker?: string;
=======
>>>>>>> origin/main
  /**
   * Indicates that this evidence item has no linking context (no based_on or supported_by).
   * The backend may omit this flag; if undefined, the UI may derive orphan status
   * from missing based_on or other fields.
   */
  orphan?: boolean;

  /**
   * When present, this evidence item leads to the specified decisions or events.
   * Not used in this implementation but reserved for future relation graph features.
   */
  led_to?: string[];
}